### ISSUE TITLE
validate_with_humanized_errors throws exception with nested MultipleInvalidErrors

### ISSUE THREAD

**Issue by NassarS** [alecthomas/voluptuous#220] opened 2016-09-28 01:31 UTC
```
>>> Schema(All(json.loads, All({Required('x'): All(unicode, Length(min=2))})))('{"x": "a"}')
...
voluptuous.error.MultipleInvalid: length of value must be at least 2 for dictionary value @ data[u'x']

>>> validate_with_humanized_errors('{"x": "a"}', Schema(All(json.loads, All({Required('x'): All(unicode, Length(min=2))}))))
Traceback (most recent call last):
  File "/Users/nstoertz/.virtualenvs/frontend/lib/python2.7/site-packages/voluptuous/humanize.py", line 39, in validate_with_humanized_errors
    raise Error(humanize_error(data, e, max_sub_error_length))
  File "/Users/nstoertz/.virtualenvs/frontend/lib/python2.7/site-packages/voluptuous/humanize.py", line 26, in humanize_error
    for sub_error in validation_error.errors
  File "/Users/nstoertz/.virtualenvs/frontend/lib/python2.7/site-packages/voluptuous/humanize.py", line 26, in <genexpr>
    for sub_error in validation_error.errors
  File "/Users/nstoertz/.virtualenvs/frontend/lib/python2.7/site-packages/voluptuous/humanize.py", line 29, in humanize_error
    offending_item_summary = repr(_nested_getitem(data, validation_error.path))
  File "/Users/nstoertz/.virtualenvs/frontend/lib/python2.7/site-packages/voluptuous/humanize.py", line 11, in _nested_getitem
    data = data[item_index]
TypeError: string indices must be integers, not unicode
>>> 


```

**Comment by tusharmakkar08** [comment] 2016-09-29 05:20
Hey @NassarS 

Thanks for reporting it. I will investigate it and get back to you. 

Thanks

**Comment by tusharmakkar08** [comment] 2016-09-30 05:11
Hey @NassarS 

I am unable to reproduce the error. 

```
>>> from voluptuous import Schema, All, Length, Required
>>> from voluptuous.humanize import validate_with_humanized_errors
>>> import json
>>> Schema(All(json.loads, All({Required('x'): All(unicode, Length(min=2))})))('{"x": "a"}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "voluptuous/schema_builder.py", line 212, in __call__
    return self._compiled([], data)
  File "voluptuous/schema_builder.py", line 650, in validate_callable
    return schema(data)
  File "voluptuous/validators.py", line 264, in __call__
    raise e if self.msg is None else AllInvalid(self.msg)
voluptuous.error.MultipleInvalid: length of value must be at least 2 for dictionary value @ data['x']
>>> validate_with_humanized_errors('{"x": "a"}', Schema(All(json.loads, All({Required('x'): All(unicode, Length(min=2))}))))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "voluptuous/humanize.py", line 40, in validate_with_humanized_errors
    raise Error(humanize_error(data, e, max_sub_error_length))
voluptuous.error.Error: length of value must be at least 2 for dictionary value @ data['x']. Got None
```
I am closing this for now. 

Thanks

**Closed by tusharmakkar08** 2016-09-30 05:11 UTC

**Comment by tusharmakkar08** [comment] 2016-09-30 05:52
Just checked in `v0.9.3` it's not fixed.  It was fixed in https://github.com/alecthomas/voluptuous/commit/a30f47fbe74b572d81040c231c792dcba2802611 .
