### ISSUE TITLE
Validation of default values

### ISSUE THREAD

**Issue by martinroos1** [alecthomas/voluptuous#233] opened 2016-10-17 15:16 UTC
It appears that default values do not go through the usual validation that would occur if a value were supplied for a given key. My use case is that I have an optional nested dictionary, which contains optional values, all of which have defaults that I want to be set. My schema is something like:

``` python
validate = Schema({
    Optional('a', default=dict): {
        Optional('b', default=1): int,
        Optional('c', default='data'): basestring
    }
})
```

My hope was that I would essentially get the result:

``` python
validate({})
>>> {'a': {'b': 1, 'c': 'data}}
```

However, due to the fact that the default value does not appear to get validated, what I actually see is:

``` python
validate({})
>>> {'a': {}}
```

I have also tried this using the `Required` marker in place of `Optional`, but this has the same outcome (which is potentially bad since the required value is not actually there). Is it an intentional design decision to not validate defaults, and if so, what is the recommended method of doing this so that I avoid repeating the data structure (obviously I could write a function for the default that generated the default dictionary, but that will repeat this information)?

**Comment by efficiosoft** [comment] 2018-02-17 19:02
I think this one should be closed now as well, since it's a duplicate of the closed https://github.com/alecthomas/voluptuous/issues/264.

**Closed** 2020-09-22 08:20 UTC
